# Generated by Django 4.2 on 2025-07-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
