# Generated by Django 4.2 on 2025-07-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_discount_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Beverage'), ('fashion', 'Fashion'), ('electronics', 'Electronics'), ('health', 'Health & Beauty'), ('home', 'Home & Living'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
