# Generated by Django 4.2 on 2025-07-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_discount_category'),
    ]

    operations = [
    ]
